name: shoescleaningapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  get: ^4.6.6
  responsive_sizer: ^3.1.0
  google_fonts: ^6.2.1
  card_swiper: ^2.0.4
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/banner/
    - assets/icon/
    - assets/recomendation/
    - assets/shoes/
    - assets/toko/
  uses-material-design: true
